/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoStatus = IDL.Variant({
  'processing' : IDL.Null,
  'ready' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Video = IDL.Record({
  'id' : IDL.Text,
  'dislikeCount' : IDL.Nat,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'videoBlobId' : IDL.Text,
  'thumbnailBlobId' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
  'uploaderUserId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'bannerBlobId' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const Channel = IDL.Record({
  'bannerBlobId' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'likeCount' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'authorUserId' : IDL.Principal,
  'videoId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([IDL.Principal], [Channel, IDL.Nat], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribedToChannel' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func([IDL.Text], [], []),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
  'unsubscribeFromChannel' : IDL.Func([IDL.Principal], [], []),
  'updateVideoStatus' : IDL.Func([IDL.Text, VideoStatus], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoStatus = IDL.Variant({
    'processing' : IDL.Null,
    'ready' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Video = IDL.Record({
    'id' : IDL.Text,
    'dislikeCount' : IDL.Nat,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'videoBlobId' : IDL.Text,
    'thumbnailBlobId' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
    'uploaderUserId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'bannerBlobId' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const Channel = IDL.Record({
    'bannerBlobId' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'likeCount' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'authorUserId' : IDL.Principal,
    'videoId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([IDL.Principal], [Channel, IDL.Nat], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribedToChannel' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func([IDL.Text], [], []),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
    'unsubscribeFromChannel' : IDL.Func([IDL.Principal], [], []),
    'updateVideoStatus' : IDL.Func([IDL.Text, VideoStatus], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };