/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'bannerBlobId' : [] | [string],
  'userId' : Principal,
  'name' : string,
  'description' : string,
  'avatarBlobId' : [] | [string],
}
export interface Comment {
  'id' : string,
  'likeCount' : bigint,
  'createdAt' : Time,
  'text' : string,
  'authorUserId' : Principal,
  'videoId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'bannerBlobId' : [] | [string],
  'createdAt' : Time,
  'avatarBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'dislikeCount' : bigint,
  'status' : VideoStatus,
  'title' : string,
  'duration' : bigint,
  'likeCount' : bigint,
  'videoBlobId' : string,
  'thumbnailBlobId' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'viewCount' : bigint,
  'commentCount' : bigint,
  'category' : string,
  'uploaderUserId' : Principal,
}
export type VideoStatus = { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[Principal], [Channel, bigint]>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getLikedVideos' : ActorMethod<[], Array<Video>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribedToChannel' : ActorMethod<[Principal], boolean>,
  'likeComment' : ActorMethod<[string], undefined>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'subscribeToChannel' : ActorMethod<[Principal], undefined>,
  'unsubscribeFromChannel' : ActorMethod<[Principal], undefined>,
  'updateVideoStatus' : ActorMethod<[string, VideoStatus], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, Array<string>, string, string, string, bigint],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];